FROM node:19-alpine as build-stage
WORKDIR /app

COPY ./build /app/build
COPY ./default.conf /app

FROM nginx:1.15
COPY --from=build-stage /app/build/ /usr/share/nginx/html
COPY --from=build-stage /app/default.conf /etc/nginx/conf.d/default.conf